### ISSUE TITLE
Need doc add listener in services

### ISSUE THREAD

**Issue by hidabe** [sopinet/upload-magic-bundle#2]
```
    sopinet.uploadlistener:
        class: Sopinet\Bundle\UploadMagicBundle\Listener\UploadListener
        arguments: ['@doctrine']
        tags:
            - { name: kernel.event_listener, event: oneup_uploader.post_persist, method: onUpload }
```
